name: artifact

on: push

env:
   FILE_NAME: hello-world

jobs: 
    build:
         runs-on: ubuntu-latest
         steps:
         - name: Actions Checkout
           uses: actions/checkout@v1

         - name: Setup Node
           uses: actions/setup-node@v4
           with:
              node-version: 18

         - name: Execute the file
           run: node ${{env.FILE_NAME}}.js

         - name: Upload artifact
           uses: actions/upload-artifact@v1.0.0
           with: 
               name: linux
               path: ./${{env.FILE_NAME}}
               
    test-linux: 
      name: Test Linux
      runs-on: ubuntu-latest
      needs: build
      steps:

      - name: Check out code
        uses: actions/checkout@v1

      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: linux

      - name: Test ${{ env.FILE_NAME }}
        run: source ./test.sh
